import requests
from bs4 import BeautifulSoup


#Retrieves a requests.Response object and stores it in page variable
def pageget():
    URL = "https://www.centralbank.go.ke/forex/"
    page = requests.get(URL)
    return page


#Get DOM info from page and filter by "td" class and class name, first 6 lines only
def resultget():
    soup = BeautifulSoup(pageget().content, "html.parser")
    results = soup.find_all("td", class_="tg-4eph")
    list_of_currencies = []
    for el in results[:6]:
        list_of_currencies.append(el.text)
    return list_of_currencies


#create individual lists then a dictionary of currencies and values from the lists we generated by resultget()
currency = resultget()[:6:2]
value = resultget()[1:6:2]
list_of_currency = dict(zip(currency, value))


#function to map currency key to correspoonding values
def get_value(curr_name):
    return list_of_currency[curr_name]
